### PR TITLE
Update strings.xml for french translation + add "get it on fdroid" button

### PR DESCRIPTION
**Pull request by Poussinou**
One of the word was badly translated

Add the "get it on fdroid" button next to the amazon one

### CODE REVIEW

**Comment by ultramega** [comment]
What is fdroid? I don't know if I want to link to a source that I don't control.

**Comment by Poussinou** [comment]
F-droid is a repo with only the interesting free and open-source applications for android (f-droid = FOSS-Droid). It works like google play store, with updates and descriptions (https://f-droid.org/repository/browse/?fdfilter=elementary&fdid=com.ultramegatech.ey)

Elementary is available on f-droid for a long time, at least one or two years. I don't know who updates the new release. I thought you were aware that Elementary was in fdroid repo, if you want, you can ask and they will surely remove your application. You can also upload the new release yourself. ;)

Personally, I discovered Elementary thanks to F-Droid, and that's the reason why I'm here to translate Elementary in french (the same for the Brazilian Portuguese translation I think). I think you can trust F-Droid;)
You can talk with @est31 I know he uploads some applications in F-Droid...

**Comment by ultramega** [comment]
Alright I'll see if I can claim control of the app and then merge this PR. I'd like to make sure updates are synchronized and stuff across all the stores.

**Comment by est31** [comment]
F-Droid logo
[F-Droid](https://f-droid.org) is an Android app store exclusively for **open source** apps. See F-Droid's [Wikipedia page](https://en.wikipedia.org/wiki/F-Droid).

As a list of open source apps, F-Droid does not give direct control over the apks to the app developers: the app's source code is taken from upstream (that is you!), and automatically built using a metadata file. This way its ensured that the app is fully open source and corresponds the source code published. The repository which contains the metadata files for all apps on F-Droid is organized with a public [gitlab repo](https://gitlab.com/fdroid/fdroiddata/), anybody (including you of course) can inspect it and propose changes via merge requests.

**Comment by ultramega** [comment]
Alright now I see how it works. Thanks for the explanation.

**Comment by Poussinou** [comment]
Thanks for your work:)

**Pull request merged**
