### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Poussinou**
Ok here is the french translation, feel free to push updates to improve this translation.

Something else : I think the last logo was better (I did a "survey" on my own, in my chemistry class, and they all think the Ey logo was more beautiful ;) )

### CODE REVIEW

**Comment by ultramega** [comment]
Thanks for the translation. Can you also translate the store description (info https://github.com/ultramega/elementary/wiki/Translations#store-description)?

Also thanks for the feedback about the new logo. I personally never really liked the old one. It was more of an afterthought. I think one works better on Windows.

**Comment by Poussinou** [comment]
Sure I can translate the store description, just give me some time ;)
I just don't know how to create a "feature.png" file in french, and the different files in screenshots... You do it?

The choice of the logo is yours...

I don't need any credit for the translations

**Comment by Poussinou** [comment]
It's done ;)

I think you can close the last issue

**Comment by ultramega** [comment]
Excellent. I can create the screenshots and feature image. Thanks again for the contribution.

I will consider changing the logo back for the Android version.

**Pull request merged**
