### PR TITLE
Norwegian (nb) translation

### PR DESCRIPTION
**Pull request by FTno**
Norwegian (nb) translation for Elementary

### CODE REVIEW

**Comment by stevotvr** [comment]
Thanks for the translation, but can you combine all your changes into this pull request? Also, for the translation to be complete, we need the text files in app/src/main/play.

**Comment by FTno** [comment]
Here are the 2 additional files (don't know how to combine in another way)

[nb_translations.zip](https://github.com/ultramega/elementary/files/2490873/nb_translations.zip)

**Comment by stevotvr** [comment]
You just need to commit the files to your patch-1 branch. I can add the files myself if you can't figure it out. Either way I still need the store description files translated before I can add this (look in `app/src/main/play` for examples). I can make the screenshots, so don't worry about that.

**Comment by FTno** [comment]
Here are description translations

[play_translations.zip](https://github.com/ultramega/elementary/files/2490805/play_translations.zip)

**Comment by stevotvr** [comment]
The translation has been added to the source repo. Thanks again for the contribution.

**Pull request closed without merging**
